# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Yarn
        allowPrerelease: false
      settings:
        id: Yarn.Yarn
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Node.js
        allowPrerelease: false
      settings:
        id: OpenJS.NodeJS
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Python 3.10
        allowPrerelease: false
      settings:
        id: Python.Python.3.10
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install VS Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode.1.76.2
        source: winget
    - resource: NpmDsc/NpmInstall
      dependsOn:
        - npm
      directives:
        description: Run 'npm install'
        allowPrerelease: true
      settings:
        PackageDirectory: '${WinGetConfigRoot}\..\'
  configurationVersion: 0.2.0